name: buildx

on:
  push:
    branches:
      - master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set tag to beta
        if: endsWith(github.ref, '/beta')
        run: |
          echo "::set-env name=TAG::beta"
      -
        name: Set tag to latest
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=TAG::latest"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=false" \
            --tag jakowenko/watchtower:${TAG} \
            --file ./dist/Dockerfile ./dist
      -
        name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Docker Buildx (push)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            --tag jakowenko/watchtower:${TAG} \
            --file ./dist/Dockerfile ./dist
      -
        name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery jakowenko/watchtower:${TAG}
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json