name: buildx

on:
  push:
    branches:
      - feature/**

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set tag to beta
        run: |
          echo "::set-env name=TAG::beta"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Docker Buildx (build)
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=false" \
            --tag jakowenko/watchtower:${TAG} \
            --file ./docker/Dockerfile ./docker
      -
        name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Docker Buildx (push)
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --tag jakowenko/watchtower:${TAG} \
            --file ./docker/Dockerfile ./docker
      -
        name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery jakowenko/watchtower:${TAG}
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json